# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with an official Drupal image that includes PHP
FROM drupal:9.4

# Set the working directory
WORKDIR /var/www/html

# Install the required PHP extension for IP handling
RUN apt-get update && apt-get install -y \
    php-ip2location \
    && rm -rf /var/lib/apt/lists/*

# Copy the module into the Drupal modules directory
COPY . /var/www/html/modules/custom/ip_login

# Set the file permissions (Drupal specific)
RUN chown -R www-data:www-data /var/www/html/modules/custom/ip_login

# Enable the module via Drush (Drupal shell)
RUN drush en ip_login -y

# Expose the port Drupal runs on
EXPOSE 80

# Use the default command provided by the Drupal base image
CMD ["apache2-foreground"]
